### ISSUE TITLE
Responsivity

### ISSUE THREAD

**Issue by NagyIlles03** [14A-B-ProjectDiscite/frontend#10]
Make the whole page responsive
![kép](https://user-images.githubusercontent.com/113507816/226561695-613c452b-4440-4280-95f3-6cd34bdc030e.png)
![kép](https://user-images.githubusercontent.com/113507816/226562217-a6459106-0549-4b27-827a-1f89122168fe.png)

**Comment by KondorArminAron23** [comment]
Responsivity done.
