### ISSUE TITLE
Wrong error toast

### ISSUE THREAD

**Issue by NagyIlles03** [14A-B-ProjectDiscite/frontend#9]
![kép](https://user-images.githubusercontent.com/113507816/226557914-71875a6a-982b-47d8-87ee-651fa7e64a8e.png)
![kép](https://user-images.githubusercontent.com/113507816/226557989-a8db6c57-b616-47a4-84bb-d4bf4495df9b.png)

**Comment by KondorArminAron23** [comment]
Fixed this bug.
